export const videos = (req, res) => res.send('videos')
export const upload = (req, res) => res.send('upload the video')
export const videoDetail = (req, res) => res.send('about videos')
export const editVideo = (req, res) => res.send('edit video')
export const deleteVideo = (req, res) => res.send('delete video')
